### ISSUE TITLE
get-color() should use relative paths

### ISSUE THREAD

**Issue by Kronuz** [ismamz/postcss-get-color#2]
`get-color(image)` gets image relative not to the current file calling the function; it should, instead, use relative paths.

For example, in file `path/to/scss/test.scss` with content like this:
```scss
.bg {
    background: get-color("../images/image.png") url("../images/image.png");
}
```
should work, but instead it tries to open a file in the working directory which is (may) not the same as the path the css file is.
